version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_miel
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_miel
      MYSQL_USER: miel_user
      MYSQL_PASSWORD: miel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - miel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    image: apimiel
    container_name: backend_miel
    ports:
      - "7000:7000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ecommerce_miel
      DB_USER: miel_user
      DB_PASSWORD: miel_password
    networks:
      - miel_network

networks:
  miel_network:
    driver: bridge

volumes:
  mysql_data: